### ISSUE TITLE
Support multiple load_balancer entries

### ISSUE THREAD

**Issue by svrc** [cloudfoundry/bosh-azure-cpi-release#111]
Hi all, here's a scenario , let me know what you think of it
1.  It is good to have split horizon DNS for a CF instance, i.e. on the devbox you have a named/bind9 server that resolves *.cf.azurelovecf.com to 10.10.16.4 inside the VNet, and the Public IP outside the VNet.   This avoids hairpin NAT routing to the load balancer public IP address which sometimes can be slower and flaky than remaining within the VNet.
2.  In a high availability enterprise scenario, we should use an Azure Load Balancer created ahead of time and have it load balance to two HAproxy instances annotated with the **load_balancer** cloud property.
3. However an azure load balancer can only have a Public OR a Private IP address, it cannot have both.
4. Therefore I think it makes sense to be able to have two (or more?)  **load_balancer** entries, one for a Private load balancer and one for a Public load balancer.   

Let me know if this is a reasonable enhancement.  Right now as workaround, I'd need to create two resource pools and jobs for haproxy.

**Comment by AbelHu** [comment]
@svrc-pivotal It is a good idea. Let us do some investigation.

**Comment by AbelHu** [comment]
Related to https://github.com/Azure/azure-powershell/issues/2042

**Comment by AbelHu** [comment]
@svrc-pivotal Now Azure has supported to create one external LB and one internal LB in the same NIC. Could you have a try?

**Comment by AbelHu** [comment]
@svrc-pivotal Need to correct. Azure can support to create create one external LB and one internal LB in the same NIC but the port rules cannot be same. We are still investigating.

**Comment by gossion** [comment]
There is a question and answer at this [link](http://stackoverflow.com/questions/34781307/associate-azure-arm-vm-with-multiple-load-balancers) about multiple load balancers, saying that:
  1. Azure NICs can participate in multiple load-balancer: one external and one internal.
  2. LB rules on the external and internal load-balancers cannot use the same backend port.
  3. Only the primary NIC can be used in load-balancer backend pools.

I had tried to create rule tcp 22:22 for both external and internal load balancers and assigned those two lbs to the same VM, I got error code "RulesUseSameBackendPortProtocolAndIPConfig" when creating the VM. 

Hi @svrc-pivotal, are you expecting to use same backend port in load balancers in CF? Azure does not support such feature now.

**Comment by gossion** [comment]
Hi @svrc-pivotal , 

Now in Azure the secondary NICs can also be used in LB backend pools, so this feature is doable. However, the secondary NICs can't be probed by LB because by default the outbound traffic will go to gateway of primary NIC. In order to make LB work with the secondary NICs we need to configure a policy route in the VM, which means we need a bosh release to configure the network additionally. I had a [PR](https://github.com/cloudfoundry/networking-release/pull/14) in [networking-release](https://github.com/cloudfoundry/networking-release), trying to implement the policy routing for this scenario, but it is not reviewed / merged yet.

It looks like this is not a common scenario, and the issue has last for a long time. Not sure if you have already solved the issue by any other methods, so my question is - do you still need this feature?

**Comment by svrc-pivotal** [comment]
@gossion At the moment we deploy separate VMs if we need separate load balancers.  I have at least two large Azure customers deploying separate VMs for internal vs. external facing HAproxies for example. 

I guess my point was that Azure is the only cloud I know (out of AWS, OpenStack, GCP, vSphere) that requires multiple NICs for multiple load balancers, so this should be a common case.   Multi-NIC could be a workaround but seems too early.  

 You can close this issue if it doesn't look like Azure LBs will ever allow a single NIC to expose to multiple load balancers, as it's a larger concern than just this CPI :)

**Comment by svrc-pivotal** [comment]
This should work with `standard` LB skus and maybe should be revisited, especially considering SNAT with `standard` LBs requires a public LB with unused inbound rules to denote SNAT outbound IPs/ports (scenario 2 here - https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections )

**Comment by daviddob** [comment]
Any updates regarding supporting multiple LBs attached to the same VM orchestrating via BOSH? We currently are accomplishing this using a separate piece of automation to attach the VMs after deployment to the second LB (one internal, one external), however it would be nice to simplify and eliminate the need for out of band changes.

**Comment by daviddob** [comment]
Not stale - waiting on updates from the BOSH team.

**Comment by MSSedusch** [comment]
this issue should be fixed with PR #638 which was released with v37.6.0.
