### ISSUE TITLE
Query regarding network watcher linux agent

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry/bosh-azure-cpi-release#307]
Hi is it possible to add azure network watcher linux agent extension to cf and diego vms while deploying. I mean is there any way to add in resource groups. Thanks in advance.

**Comment by AbelHu** [comment]
@abhilash07 It is an interesting topic but it is not supported for now. We can consider to support it later.

**Comment by h4xnoodle** [comment]
Closing this issue as we are not planning on supporting this feature.

Thanks,
Rebecca, BOSH
