### ISSUE TITLE
VM can't change Availability Set while attached  to Load balancers

### ISSUE THREAD

**Issue by OlegGerber** [cloudfoundry/bosh-azure-cpi-release#368]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 32
BOSH     Version: "264.4.0"

### Stemcell
Version:
Distro:
  - [x] Ubuntu
### Environment
- Azure Environment:
  - [x] Azure

### Issue Details
Bosh unable to complete availability set recreation for the VMs attached to a load balancer's backed pool.
Machines should be removed in advance form the target list on LB pool in order to finish the deployment.

**Comment by bingosummer** [comment]
It's a known issue that the VMs attached to a load balancer must be in a same availability set. In the scenario of changing the availability set name, BOSH director calls CPI to delete/create the VMs one by one. So CPI don't have the ability to delete other VMs in advance from the LB pool.

* Would you like to use availability zones instead of availability set?

* If availability set is a MUST, we will try to look for a workaround for the issue, and keep you posted later.

* Could you please share why you need to change the availability set name?

**Comment by OlegGerber** [comment]
Q:---Would you like to use availability zones instead of availability set?---
A: Yes, but AFAK this feature is not GA

Q:----Could you please share why you need to change the availability set name?---
A: To enable VM type upgrade issue (https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/367 )

**Comment by bingosummer** [comment]
There are two ways I can think of:

Option 1:
Change the availability set name and load balancer name together. Deploy. Then the new VMs will be created in a new availability set and associated with the new load balancer. As a result, the public IP to enter CF is changing. You need to resolve the domain name to the new public IP address.

Option 2:
1. Detach the load balancer, and change the availability set name. Deploy.
2. Re-attach the load balancer to the VMs. Deploy.

However, both options have downtime from the point view of CF runtime.

**Comment by bingosummer** [comment]
The VMs attached to a Basic SKU load balancer must be in a same availability set. But Standard SKU LB doesn't have the limitation.
@cwlbraa can you try standard LB?

**Comment by cwlbraa** [comment]
More meaningful error messages would be "better online feedback," yeah. 

In this case i'm uncertain if the CPI should even allow basic SKU'd lbs to be used at all. If we disallowed them, an error (or validation) message that says "basic lbs are unsupported: use a standard sku load balancer" would be great. 

If we should allow basic SKU'd lbs, an error message that said "availability sets attached to basic SKU load balancers can not be recreated" would help, but I'd also like a similar message in the case I described above-- it'd be something like: "The basic sku'd lb Z is already attached to availability set X, so it can't be attached to availability set Y. Please use standard sku load balancers."

**Comment by bingosummer** [comment]
Thanks for your feedback.
CPI allows basic SKU LBs. I agree that CPI should provide something like "The basic sku'd lb Z is already attached to availability set X, so it can't be attached to availability set Y. Please use standard sku load balancers."
