### ISSUE TITLE
Refine the retry logic in CPI

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-azure-cpi-release#443]
CPI has many retries. Are they neccessary?
Some retry timeout is too long (it is recommended by Azure API). Should we reduce the retry timeout?

**Comment by ClaudiaBaur** [comment]
If a certain VM size is not available in the Azure DC, the logic of the bosh-azure-cpi retries 10 times to create the VM with a retry sleep of 480 seconds  after each failure. Finally, this leads to a returning time of 1h 40 minutes. Is there a way to make the amount of retries configurable?

see also:
response.body: {"startTime":"2019-12-16T20:51:11.9137023+00:00","endTime":"2019-12-16T20:51:51.429896+00:00","status":"Failed","error":

{"code":"ZonalAllocationFailed","message":"Allocation failed. *We do not have sufficient capacity for the requested VM size in this zone.* Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance"}
,"name":"246b7307-0e08-4e60-b2ff-d10c3d1e6af6"}
W, 2019-12-16T20:51:52.212925 #118218 #47386358501200 WARN – [req_id cpi-803040]: check_completion - http_put fails for an AzureAsynInternalError. **Will retry after 480 seconds**. 

I, 2019-12-16T22:33:44.776764 #118218 INFO – [req_id cpi-803040]: **Finished create_vm in 6160.84 seconds**

Thanks & best, Claudia

**Comment by jastev** [comment]
We should distinguish between a given VM family not being available generally (which can be known up front) from a capacity issue preventing a nominally provisionable request from being satisfied at the moment (which isn’t).  For the former, we should detect that at request-time and abort without retry, whereas for the latter retries may be ultimately successful (especially in the repave case, where a VM has just been retired).

**Comment by ClaudiaBaur** [comment]
No retry in case of an 'out of capacity' issue would also be fine with us. Currently, the code behaviour of bosh-azure-cpi blocks everything due to the ways too long timeout in that case. If it helps, I can also provide the logs.
Thanks, Claudia
