### ISSUE TITLE
provide one way for customer to config the maximum data disk count in cpi or call api to retrieve it.

### ISSUE THREAD

**Issue by andyliuliming** [cloudfoundry/bosh-azure-cpi-release#503]

**Comment by gossion** [comment]
suggest using API 'https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinesizes/list#virtualmachinesize'

**Comment by andyliuliming** [comment]
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinesizes/list#virtualmachinesize

**Comment by andyliuliming** [comment]
@bingosummer I'm not saying to let customer config the max data disk count for every instance.
I mean provide one way for customer "override" it.
and also get it from the api is a good way too.
