### ISSUE TITLE
Managed Disks support in Azure Stack

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-azure-cpi-release#508]
https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-managed-disk-considerations

Blocker:
- [ ]  managed custom image is not yet supported

**Comment by bottkars** [comment]
with 1811, we have custom image support in azure stack.
However, selecting managed disks calls for the wrong compute api ( 2015.06.15 instead of 2017.03.30 )
using CPI 35.5
` Creating instance 'bosh/0':
   Creating VM:
     Creating vm with stemcell cid 'bosh-stemcell-7f3aad8f-32a8-47f3-ae87-dbe1a51559f5':
       CPI 'create_vm' method responded with error: CmdError{"type":"Bosh::Clouds::VMCreationFailed","message":"#\u003cBosh::Clouds::VMCreationFailed: Failed to get the user image information for the stemcell 'bosh-stemcell-7f3aad8f-32a8-47f3-ae87-dbe1a51559f5': #\u003cBosh::AzureCloud::AzureError: http_put - http code: 400\nx-ms-client-request-id: \nx-ms-request-id: 607bcd9f-73ca-4770-a139-61841ca1d1f9\nx-ms-correlation-request-id: 607bcd9f-73ca-4770-a139-61841ca1d1f9\nx-ms-routing-request-id: LOCAL:20190103T153715Z:607bcd9f-73ca-4770-a139-61841ca1d1f9\nError message: {\"error\":{\"code\":\"NoRegisteredProviderFound\",\"message\":\"No registered resource provider found for location 'local' and API version '2015-06-15' for type 'images'. The supported api-versions are '2017-03-30'. The supported locations are 'local'.\"}}\u003e\n/home/tempest-web/.bosh/installations/3c05a3c8-4525-463c-73a0-7400495db519/packages/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb:2369:in `check_completion'\n/home/tempest-web/.bosh/installations/3c05a3c8-4525-463c-73a0-7400495db519/packages/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb:2458:in `http_put'\n/home/tempest-web/.bosh/installations/3c05a3c8-4525-463c-73a0-7400495db519/packages/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb:1017:i`

**Comment by bingosummer** [comment]
Thanks @bottkars for your information.
You are right. To support managed disks in Azure Stack, the api should be upgraded to `2017-03-30`.
CC @NingKuang

**Comment by jbpaux** [comment]
Would it be possible to bump API version in https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/utils/helpers.rb ?
We'd like to deploy using managed disks.

**Comment by cfBrianMiller** [comment]
@bingosummer There is a blocker here that managed custom images are not supported. Is this still the case, it doesn't appear to be and I have validated it's possible on an azure stack environment.

[Microsoft Documentation](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-managed-disk-considerations?view=azs-2002#managed-images)

Thank you

**Comment by bingosummer** [comment]
@cfBrianMiller I think, it's not a blocker now. But I'm not working on Azure CPI now.
Would you or anyone else like to help on this?
