### ISSUE TITLE
we should find the security group from more places, say, the resource group which the vm are in.

### ISSUE THREAD

**Issue by andyliuliming** [cloudfoundry/bosh-azure-cpi-release#525]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version:
BOSH     Version:
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

**Comment by bingosummer** [comment]
https://github.com/cloudfoundry-incubator/bosh-azure-cpi-release/issues/328

**Comment by bingosummer** [comment]
@andyliuliming Please update the assumption for the PR #541 . Then we can document it later to avoid confusing users.

**Comment by andyliuliming** [comment]
PR: https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/541
fixed this. please wait for the next release of CPI.
config it like this:
vm_extensions:
- cloud_properties:
    resource_group_name: ((cfcr_resource_group_name))
    load_balancer:
      resource_group_name: ((cfcr_resource_group_name))
      name: ((cfcr_master_loadbalancer_name))
    security_group:
      resource_group_name: ((cfcr_resource_group_name))
      name: ((cfcr_master_security_group))
  name: ((deployment_name))-master-cloud-properties





- type: replace
  path: /networks/-
  value:
    name: cfcr
    subnets:
    - azs:
      - z1
      - z2
      - z3
      gateway: ((cfcr_internal_gw))
      range: ((cfcr_subnet_cidr))
      reserved:
      - ((cfcr_internal_gw))/30
      cloud_properties:
        virtual_network_name: ((cfcr_vnet_name))
        subnet_name: ((cfcr_subnet))
        security_group:
          resource_group_name: ((cfcr_resource_group_name))
          name: ((cfcr_master_security_group))
    type: dynamic

**Comment by andyliuliming** [comment]
and sample for availability_set

availability_set:
  platform_update_domain_count: ((platform_update_domain_count))
  platform_fault_domain_count: ((platform_fault_domain_count))
  name: ((name))
