### ISSUE TITLE
Windows server 2016 support

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-azure-cpi-release#532]
Check whether CPI works well with windows server 2016 stemcell

**Comment by bingosummer** [comment]
Ephemeral Disk is supported for the Windows Server, version 1709-based stemcells as well as Windows Server, version 1803-based stemcells! Not supported on 2012-based stemcell.

**Comment by h4xnoodle** [comment]
We expect that this works and folks have run it before. Also 2016 stemcells are getting quite old at this point.
