### ISSUE TITLE
use the os disk type in vm instead of sticking to image type.

### ISSUE THREAD

**Issue by andyliuliming** [cloudfoundry/bosh-azure-cpi-release#533]

**Comment by bingosummer** [comment]
1. CPI creates the managed image with a `Standard_LRS` storage account type.
1. CPI specifies the managed disk's `StorageAccountType` when creating VM.
https://github.com/Azure/azure-rest-api-specs/blob/607f4971fda3a3604dd3540067b9221d2029bc8e/specification/compute/resource-manager/Microsoft.Compute/stable/2018-04-01/compute.json#L5194-L5197
