### ISSUE TITLE
Update CPI methods after BOSH registry is removed in CPI contract v2

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-azure-cpi-release#536]
The community is actively removing BOSH registry from CPI contract. The plan for now is to add the capability in the Director, Agent, and CPIs so that they can **bypass** the registry all and do not require it anymore.
In CPI contract v2, several CPI methods don't need to connect to BOSH registry to update the settings. They just need to be return the updated settings as the result. Director will handle them.

Note: The registry job in the Director will **NOT** be removed. For backwards compatibility reasons, the registry job will remain there in case one of these 3 components (Director, Agent, CPI) does not support the new contract, so that it can safely fallback to registry.

Currently, this issue is only for tracking.
https://github.com/cloudfoundry/bosh-notes/blob/master/proposals/cpi-api-v2.md

**Comment by h4xnoodle** [comment]
Delivered in https://github.com/cloudfoundry/bosh-azure-cpi-release/pulls/606
