### ISSUE TITLE
Register VM settings to bosh registry before VM is ready

### ISSUE THREAD

**Issue by gossion** [cloudfoundry/bosh-azure-cpi-release#542]
## Issue
Currently Azure CPI uses `bosh registry` for its VM Config Metadata, and the steps of creating a missing VM are:
### On bosh director side
A. bosh director calls CPI to create VM
B. CPI creates the VM according to its vm_properties
C. CPI **waits** until VM is ready
D. CPI registers `VM settings` to `bosh registry`
E. bosh director try to `ping` the VM, and **wait** until VM responses a `pong` message.
F. Once bosh director receives a pong response from VM, bosh will go on with creating VM (requestS VM to update_setting, apply packages, etc)
G. creating action is done

### On bosh agent side
a. VM boots up, and bosh agent starts
b. bosh agent **waits** until `VM settings` is available in `bosh registry`
c. bosh agent read `VM settings` from bosh registry
d. bosh agent re-configures its network according to `VM settings`
e. bosh agent prepares ephemeral disk according to `VM settings`
f. bosh agent is ready to receive requests
g. bosh agent gets `ping` action from bosh director (sent by step `E`), and then response a `pong` message
h. bosh agent continues to receive requests from bosh director

Normally it takes **~12 seconds** on step `E`, at that time bosh agent is going through steps `c,d,e,f,g`. It is a lot of time wasted.

## Proposal
It is possible to remove this waiting time if CPI moves step `D` to ahead of `B`, so bosh agent does not need to wait long in step `b`, and then steps `c,d,e,f,g` can be running in parallel with step `C`. Ideally, bosh director can save ~12 seconds when creating a VM.

## Actions
Need to investigate if there is any side effect on this change
1. any conflict with wala
2. if it works with both linux and windows
3. what happens if bosh registry has a record for VM but the VM does not exist / available at that time
4.

**Comment by bingosummer** [comment]
In near future, the CPI documentation will be updated for CPI contract v2. See #536 
You may want to take the CPI v2 into account.

**Comment by h4xnoodle** [comment]
The registry is now deprecated as of https://github.com/cloudfoundry/bosh-azure-cpi-release/pulls/606
