### ISSUE TITLE
Enable Azure Blob storage support for the BOSH director

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-azure-cpi-release#545]
**Is your feature request related to a problem? Please describe.**
Currently the BOSH director supports WebDAV, GCS, and S3 for its Blobstore Providers. As a primarily Azure-based operator, not having parity on blob storage adds a small engineering overhead which may not necessarily exist in AWS and GCP.

**Describe the solution you'd like**
- [ ] Azure blobstore provider. https://github.com/bingosummer/bosh-azureblobcli
- [ ] Add the Azure blobstore provider to BOSH. https://github.com/bingosummer/bosh/tree/add-azureblob-cli
- [ ] PR to Azure CPI. https://github.com/bingosummer/bosh-azure-cpi-release/tree/add-native-azure-storage-support
- [ ] PR to Azure stemcell. https://github.com/bingosummer/bosh-linux-stemcell-builder/tree/add-azureblobcli
- [ ] PR to bosh-cli for https://bosh.io/docs/release-blobs/

**Comment by bingosummer** [comment]
CC @mxplusb @mfine30

**Comment by mxplusb** [comment]
//cc @jastev

**Comment by mxplusb** [comment]
Can you please update the PR links with formal PR links? Currently they are just repo links.

**Comment by bingosummer** [comment]
These code changes are made some times ago. I will rebase them and submit them. Then I will keep you posted.

**Comment by jpluscplusm** [comment]
Does this feature still look like it's anywhere on the roadmap?

**Comment by mvach** [comment]
The azure-storage-cli is located in https://github.com/cloudfoundry/bosh-azure-storage-cli now.
