### ISSUE TITLE
Enable TLS 1.2+ in Azure Storage Ruby Client side

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-azure-cpi-release#546]
**Is your feature request related to a problem? Please describe.**
As mentioned in https://docs.microsoft.com/en-us/azure/storage/common/storage-security-tls, TLS 1.2 or newer version should be enabled in client side before sending requests to operate Azure Storage service.

**Describe the solution you'd like**
- [x] Expose faraday's ssl config in the storage client level.
- [x] Release a new version of azure-storage-ruby.
- [x] Bump to the new version in CPI
- [ ] Test on Azure and Azure Stack

**Additional context**
* https://github.com/Azure/azure-storage-ruby/issues/129
* After this change, the older versions than Azure Stack 1802 update are not supported any longer. Because the latest azure-storage-ruby's storage service API version is only supported by 1802 update or newer, https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-acs-differences#api-version. I think it's OK, because the older versions than 1802 update are not in support by Azure Stack team.

**Comment by andyliuliming** [comment]
update: storage team confirmed that the new sdk would be released in mid-nov.

**Comment by bingosummer** [comment]
https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/605 upgrades the azure storage sdk to v1.1.0.
