### ISSUE TITLE
sometimes we got container already exists.

### ISSUE THREAD

**Issue by andyliuliming** [cloudfoundry/bosh-azure-cpi-release#572]
Failed to prepare the config disk, Error: #<Bosh::Clouds::CloudError: Failed to upload page blob: inspect:#<Azure::Core::Http::HTTPError:47175437464320 @http_response: #<Azure::Core::Http::HttpResponse:0x000055cfc6626678 @http_response=#<Faraday::Response:0x000055cfc66266c8 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:put @body="\xEF\xBB\xBF<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.\nRequestId:4b5eb16c-801e-0069-738d-66c441000000\nTime:2018-10-18T02:51:00.8123262Z</Message></Error>" @url=#<URI::HTTPS https://22486da1202a8c2c6bb0fa0f.blob.core.windows.net/azure-config-disks?restype=container> @request=#<Faraday::RequestOptions open_timeout=60> @request_headers={"User-Agent"=>"Azure-Storage/1.0.1-1.0.1 (Ruby 2.4.4-p296; Linux linux-gnu)", "x-ms-date"=>"Thu, 18 Oct 2018 02:51:00 GMT", "x-ms-version"=>"2016-05-31", "DataServiceVersion"=>"1.0;NetFx", "MaxDataServiceVersion"=>"3.0;NetFx", "Content-Type"=>"application/atom+xml; charset=utf-8", "x-ms-client-request-id"=>"507c2f69-f81d-4d6a-be93-277661035c05", "Content-Length"=>"0", "Authorization"=>"SharedKey 22486da1202a8c2c6bb0fa0f:MVPeLyZmA5tSbwfmkni2aIgJ0x8NNNPE+YL5oBtJRxI="} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x000055cfc66266c8 ...> @response_headers={"content-length"=>"230", "content-type"=>"application/xml", "server"=>"Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0", "x-ms-request-id"=>"4b5eb16c-801e-0069-738d-66c441000000", "x-ms-version"=>"2016-05-31", "date"=>"Thu, 18 Oct 2018 02:50:59 GMT", "connection"=>"close"} @status=409 @reason_phrase="The specified container already exists.">>, @uri=#<URI::HTTPS https://22486da1202a8c2c6bb0fa0f.blob.core.windows.net/azure-config-disks?restype=container>>, @uri: #<URI::HTTPS https://22486da1202a8c2c6bb0fa0f.blob.core.windows.net/azure-config-disks?restype=container>, @status_code: 409, @type: "ContainerAlreadyExists", @description: "The specified container already exists.\nRequestId:4b5eb16c-801e-0069-738d-66c441000000\nTime:2018-10-18T02:51:00.8123262Z">

**Comment by bingosummer** [comment]
It may be a race condition when two processes are creating the same container at the same time.

**Comment by andyliuliming** [comment]
@bingosummer yes, it is.

**Comment by andyliuliming** [comment]
PR to fix this: https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/574
@bingosummer  please help do a review.
