### ISSUE TITLE
Connection reset by peer - SSL_connect

### ISSUE THREAD

**Issue by MikeJastrzebski** [cloudfoundry/bosh-azure-cpi-release#593]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 35.0.0
BOSH     Version: 265.11.0
CF       Version: 3.38.0
Diego    Version: 1.35.8

### Stemcell
Version: 3541.48
Distro: ubuntu-trusty
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ X ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US): Canada Central
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details

There is an uncaught (Connection reset by peer - SSL_connect) error which fails when running a 'bosh recreate' or 'bosh deploy --recreate' on VMs.

### Logs (*Please redact all sensitive information in your logs*)

CPI LOGS:

Rescued Unknown: Connection reset by peer - SSL_connect. backtrace: /var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:948:in `connect'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:876:in `start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/2.4.0/net/http.rb:1165:in `get'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:78:in `perform_request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:38:in `block in call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:85:in `with_net_http_connection'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/adapter/net_http.rb:33:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday_middleware-0.12.2/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/rack_builder.rb:141:in `build_response'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/faraday-0.13.1/lib/faraday/connection.rb:387:in `run_request'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/http_response_helper.rb:27:in `set_up_response'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:143:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/retry_policy.rb:41:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/retry_policy.rb:41:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/signer_filter.rb:28:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/signer_filter.rb:28:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/http/http_request.rb:104:in `block in with_filter'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/service.rb:36:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/filtered_service.rb:34:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-core-0.1.12/lib/azure/core/signed_service.rb:41:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-storage-0.12.3.preview/lib/azure/storage/service/storage_service.rb:53:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-storage-0.12.3.preview/lib/azure/storage/blob/blob_service.rb:59:in `call'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/azure-storage-0.12.3.preview/lib/azure/storage/blob/container.rb:571:in `list_blobs'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:191:in `block in list_blobs'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:414:in `block in initialize_blob_client'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:403:in `synchronize'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:403:in `initialize_blob_client'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/blob_manager.rb:185:in `list_blobs'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/disk_manager.rb:161:in `list_disks'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/storage_account_manager.rb:97:in `block in get_storage_account_from_resource_pool'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/storage_account_manager.rb:96:in `each'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/storage_account_manager.rb:96:in `get_storage_account_from_resource_pool'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:166:in `block in create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_common-1.3262.24.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/bosh_azure_cpi/lib/cloud/azure/cloud.rb:133:in `create_vm'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `public_send'
/var/vcap/packages/bosh_azure_cpi/vendor/bundle/ruby/2.4.0/gems/bosh_cpi-2.4.1/lib/bosh/cpi/cli.rb:82:in `run'
/var/vcap/packages/bosh_azure_cpi/bin/azure_cpi:39:in `<top (required)>'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `load'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:75:in `kernel_load'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli/exec.rb:28:in `run'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:424:in `exec'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:27:in `dispatch'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/cli.rb:18:in `start'
/var/vcap/packages/ruby-2.4-r3/bin/bundle:30:in `block in <main>'
/var/vcap/packages/ruby-2.4-r3/lib/ruby/site_ruby/2.4.0/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/var/vcap/packages/ruby-2.4-r3/bin/bundle:22:in `<main>'

BOSH Logs:

{"id":189375,"state":"error","description":"create deployment","timestamp":1540611846,"started_at":1540611835,"result":"Failed to acquire lock for lock:deployment:cf-64ca42fa2aaa42d711f0 uid: 4085d4cf-7e42-47f7-9e72-466453a3ebd7","user":"director","deployment":"cf-A","context_id":""}
[httpClient] 2018/10/27 03:41:52 DEBUG - Sending GET request to endpoint 'https://X.X.X.X:25555/tasks/189375/output?type=event'
[attemptRetryStrategy] 2018/10/27 03:41:52 DEBUG - Making attempt #0 for *httpclient.RequestRetryable
[clientRetryable] 2018/10/27 03:41:52 DEBUG - [requestID=61dc9069-e429-43e7-7dbf-049a4decb513] Requesting (attempt=1): Request{ Method: 'GET', URL: 'https://X.X.X.X:25555/tasks/189375/output?type=event' }

CLI Logs:

Task 189387 | 04:55:00 | Updating instance cloud_controller_worker: cloud_controller_worker/fbe8ae33-ebf3-4b30-9001-a19ad2f99995 (0) (canary) (00:01:22)
                      L Error: Unknown CPI error 'Unknown' with message 'Connection reset by peer - SSL_connect' in 'create_vm' CPI method
Task 189387 | 04:56:44 | Updating instance loggregator_trafficcontroller: loggregator_trafficcontroller/d9127036-69fb-4d37-a457-d71a317c8528 (0) (canary) (00:03:06)
                      L Error: Unknown CPI error 'Unknown' with message 'Connection reset by peer - SSL_connect' in 'create_vm' CPI method

### Repro steps (*if necessary, delete otherwise*)

1. 'bosh -e env -d deployment deploy --recreate' 
or
2. 'bosh -e env -d deployment recreate'

**Comment by gossion** [comment]
Hi @MikeJastrzebski ,
I think the error was already fixed on v35.2.0 with pr #375, which had updated storage sdk to fix a retry issue.
The error only happens in a low rate, anyway. Are you able to upgrade your cpi to latest version to include the fix?

**Comment by MikeJastrzebski** [comment]
Thanks @gossion, I'll give it a try.

And yes, it was an intermittent error.
