### ISSUE TITLE
Configure a timeout of calling Azure APIs by users

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-azure-cpi-release#601]
**Is your feature request related to a problem? Please describe.**

If users run into VM creation times of >2hrs for some reason. they have to wait for such long time to take corrective actions. It sets back the release timelines by quite a lot.

**Describe the solution you'd like**

Because of this, there is a feature request to enforce a VM creation timeout on user side. This can be configured by the end user and this way, they won’t have to wait for an indefinite amount of time to take corrective action.

**Describe alternatives you've considered**

CPI should provide a global configuration to allow customers configure the timeout of Azure API requests. If any request (create VM, delete VM, attach disk, …) to Azure API timeouts, then CPI should fail fast.

**Additional context**

**Comment by ginobiliwang** [comment]
We have had the same issue, are there any update or progress on current issue?
