### ISSUE TITLE
Deploying Micro-Bosh & CF on Hyper-V Manager Baremetal

### ISSUE THREAD

**Issue by abhilash07** [cloudfoundry/bosh-azure-cpi-release#604]
Hi everyone, is bosh-azure-cpi-release useful to deploy Micro-Bosh VM , Upload Setmcell, CF Bosh VMs creation etc, on windows 2016 datacenter Hyper-V Manager (Baremetal) (not azurestack VM).

If not, can please let me know if there's any reference for this feature. Why because many of my clients having  windows 2016 datacenter Hyper-V Manager, they want to deploy Micro-Bosh & CF and give service on baremetal same like VMware.

Thanks in Advance

Abhilash S

**Comment by bingosummer** [comment]
Azure CPI doesn't support Hyper-V manager (Baremetal). AFAIK, there's no other CPI to support it.
