### ISSUE TITLE
CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::AzureCloud::AzureError","message":"get_token - http code: 400. Azure authentication failed: Bad request

### ISSUE THREAD

**Issue by ramintagizade** [cloudfoundry/bosh-azure-cpi-release#609]
creating stemcell (bosh-azure-hyperv-ubuntu-xenial-go_agent 97.12):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::AzureCloud::AzureError","message":"get_token - http code: 400. Azure authentication failed: Bad request. Please assure no typo in values of tenant_id, client_id or client_secret/certificate. Error message: {\"error\":\"unauthorized_client\",\"error_description\":\"AADSTS700016: Application with identifier 'id1' was not found in the directory 'id2'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\\r\\nTrace ID: c3cde515-223c-4620-90fd-46799e\\r\\nCorrelation ID: 493270da-492d-4bc1-8d1e-\\r\\nTimestamp: 2019-03-31 13:59:13Z\",\"error_codes\":[700016],\"timestamp\":\"2019-03-31 13:59:13Z\",\"trace_id\":\"c3cde515-223c-4620-90fd-46799e9\",\"correlation_id\":\"493270da-492d-4bc1-8d1e-4c0aa45e\",\"error_uri\":\"https://login.microsoftonline.com/error?code=700016\"}","ok_to_retry":false}

Exit code 1

### Versions (*please add them if you have more releases for this issue*)
CPI      Version:
BOSH     Version:
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

**Comment by bingosummer** [comment]
@ramintagizade
Can you double-check whether the application with identifier 'id1' exists in the directory 'id2'?
if the application exists, can you login azure cli/powershell with your service principal?

**Comment by ramintagizade** [comment]
I solved that issue, by replacing with a new PCI, but now below error occurs , while wanting to grant a Contributor role to a new one: >az role assignment create --assignee "d00fc3c0-8b1c-4308-914e-ab" --role "Contributor" --scope /subscriptions/ad092f72-8200-4fb9-99de-0e
The client 'user@company.com' with object id 'g6ab4c39-05f0-42ed-a4ed-03a5c1' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/ad092f72-8200-4fb9-99de-0e'.

**Comment by ramintagizade** [comment]
This error occurs while i am starting bosh deployment on azure vm : 
creating stemcell (bosh-azure-hyperv-ubuntu-xenial-go_agent 97.12):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Bosh::AzureCloud::AzureError","message":"http_get - http code: 403. Error message: {\"error\":{\"code\":\"AuthorizationFailed\",\"message\":\"The client '4755fa65-6bbc-47a0-ae84-3354ada69' with object id '4755fa65-6bbc-47a0-ae84-3354ada69' does not have authorization to perform action 'Microsoft.Storage/storageAccounts/read' over scope '/subscriptions/ad092f72-8200-4fb9-99de-0e/resourceGroups/modb-chrt/providers/Microsoft.Storage'.\"}}","ok_to_retry":false}

Exit code 1

**Comment by bingosummer** [comment]
> I solved that issue, by replacing with a new PCI, but now below error occurs , while wanting to grant a Contributor role to a new one: >az role assignment create --assignee "d00fc3c0-8b1c-4308-914e-ab" --role "Contributor" --scope /subscriptions/ad092f72-8200-4fb9-99de-0e
> The client '[user@company.com](mailto:user@company.com)' with object id 'g6ab4c39-05f0-42ed-a4ed-03a5c1' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/ad092f72-8200-4fb9-99de-0e'.

The client "user@company.com" doesn't have sufficient privileges to create role assignments. See: https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal#prerequisites

**Comment by ramintagizade** [comment]
In my subscription i have a Contributor role, may be i need full admin access to write ?
