### ISSUE TITLE
CPI 35.5.2 fails on VM Creation for AzureStack

### ISSUE THREAD

**Issue by bottkars** [cloudfoundry/bosh-azure-cpi-release#613]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 35.5.2
BOSH     Version:
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [x] AzureStack
    - Version:1904
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name: ciag
- [ ] Use Managed Disks

### Issue Details
VM Creation fails when detecting LB / Public IP´s.
This is a Bosh Deployment using bosh and PCF OpsManager 2.5.5

### Logs (*Please redact all sensitive information in your logs*)

Task 22 | 20:53:19 | Creating missing vms: db/88730cf9-86b3-4d37-a094-2db70884b408 (0) (00:10:25)
Task 22 | 20:54:15 | Creating missing vms: worker/53a66597-e02c-4393-a727-ec6aa43f3c24 (0) (00:11:21)
Task 22 | 20:54:15 | [31mError: CPI error 'Bosh::Clouds::VMCreationFailed' with message '#<NoMethodError: undefined method `[]' for nil:NilClass>
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/lib/cloud/azure/restapi/azure_client.rb:2106:in `parse_public_ip'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/lib/cloud/azure/restapi/azure_client.rb:1297:in `get_public_ip'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/lib/cloud/azure/restapi/azure_client.rb:1377:in `block in _get_load_balancer'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/lib/cloud/azure/restapi/azure_client.rb:1370:in `each'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/lib/cloud/azure/restapi/azure_client.rb:1370:in `_get_load_balancer'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/lib/cloud/azure/restapi/azure_client.rb:1346:in `get_load_balancer_by_name'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/lib/cloud/azure/vms/vm_manager_network.rb:95:in `_get_load_balancer'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/lib/cloud/azure/vms/vm_manager_network.rb:144:in `block in _create_network_interfaces'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `block in synchronize'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/synchronization/mri_lockable_object.rb:38:in `synchronize'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/ivar.rb:170:in `safe_execute'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/future.rb:52:in `block in execute'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/var/vcap/data/packages/bosh_azure_cpi/d9bf7cabf156c4cf52b7cc9f9ae1ac6a21566758/vendor/bundle/ruby/2.4.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'' in 'create_vm' CPI method (CPI request ID: 'cpi-974069')[0m

**Comment by dsboulder** [comment]
Yeah, I see that I messed that up. Fill fix soon.

**Comment by dsboulder** [comment]
Fixed in 35.5.3, 36.0.1
