### ISSUE TITLE
Configuration for specification of the storage account to be used for stemcells 

### ISSUE THREAD

**Issue by ninja-at-work** [cloudfoundry/bosh-azure-cpi-release#614]
**Is your feature request related to a problem? Please describe.**
This feature can provide more control for BOSH operator to specify a dedicated storage account for stemcell instead of letting to the BOSH automatically find some storage account which may not be suitable for stemcells.

This feature would address the issue described here: https://github.com/cloudfoundry/bosh-azure-cpi-release/issues/612

**Describe the solution you'd like**
BOSH CPI should accept in configuration storage account to be used for stemcells.
When this configuration is in place, then stemcells storage account autodetection logic should be inactive.
All stemcell operations should respect this configuration and not perform lookups in any other storage account.

Thanks

**Comment by h4xnoodle** [comment]
The `use_default_account_for_cleaning` feature also provides a workaround to the stemcell issue specified here.
