### ISSUE TITLE
Support Tagging of VMs during creation time

### ISSUE THREAD

**Issue by alekssaul** [cloudfoundry/bosh-azure-cpi-release#615]
**Is your feature request related to a problem? Please describe.**
I work with an Azure customer that rolled out a new Azure policy to assert that all VM creations must have a tag. Customer uses VM tags to associate CostCenter for usage and charge the consumers appropriately within the enterprise. This policy breaks Bosh CPI for Azure as based on my understanding, creation of VM API call is different than tagging of VM API call that is made post VM creation. 

**Describe the solution you'd like**
It would be great if Bosh CPI can support assigning tags to VMs along with the VM creation API call

**Describe alternatives you've considered**
Disabling the policy that asserts VMs must be created with tags or getting enterprise exception. 

**Additional context**
I'm part of Pivotal Cloud Foundry Platform Architecture team that commonly works with Financial Customers. This impacts one of the teams I work with.

**Comment by jastev** [comment]
CPI supports assigning tags at VM creation consistent with tag-based Policies.  Aleks, I think we've established that the issue you saw is with the Policy definition, rather than the CPI, but I'll leave this open until you've verified that.
