### ISSUE TITLE
storage accounts with exhausted quota are still used for allocating vm disk

### ISSUE THREAD

**Issue by scottgai** [cloudfoundry/bosh-azure-cpi-release#618]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version:
BOSH     Version:
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details
After the space quota for existing storage accounts on Azure was exhausted, some new storage accounts were added. However seems bosh was still trying to deploy vm to old storage accounts (where storage quota already exhausted). Considering `storage_account_max_disk_number` in the cloud config is set at 150 by default, and old storage accounts have less than 150 disks, perhaps that’s reason why old storage accounts were still used?
It seems quota is not examined (only storage_account_max_disk_number is checked) per this code line.
https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/8375dce86c6f3d3632061fa6657cba7b5f540a9c/src/bosh_azure_cpi/lib/cloud/azure/vms/vm_manager_storage.rb#L35

**Comment by dsboulder** [comment]
I'm suggesting that folks try to recreate all their VMs and disks, after adding more storage accounts. That should uniformly distribute the load better, reducing the probability of this ever happening.
