### ISSUE TITLE
Hit SRP(storage account operation) throttling error in large scale deployment

### ISSUE THREAD

**Issue by thomas1206** [cloudfoundry/bosh-azure-cpi-release#619]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: latest
BOSH     Version: latest
CF       Version:
Diego    Version:

### Stemcell
Version:
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [ ] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US)
- Subscription ID:
- Resource Group Name:
- [ ] Use Managed Disks

### Issue Details
Customer has reported that they hit the SPR (storage account operation) throttling error when doing large scale deployment.

### Logs (*Please redact all sensitive information in your logs*)
Task 414003 | 10:01:46 | Error: CPI error 'Bosh::Clouds::CloudError' with message 'http_get_response - 429
x-ms-client-request-id: 8972801e-28dc-498d-9fe9-64ae2c5510e5
x-ms-request-id: fb950725-0209-44d3-9932-adfc511e951f
x-ms-correlation-request-id: 1e4d0c15-036d-477d-b4f4-be83b94a882a
x-ms-routing-request-id: WESTUS2:20190926T095833Z:1e4d0c15-036d-477d-b4f4-be83b94a882a
response.body: {"error":{"code":"TooManyRequests","message":"The request is being throttled as the limit has been reached for operation type - List. For more information, see - https://aka.ms/srpthrottlinglimits"}}http_get_response - Failed to get http response after 10 times.
' in 'set_vm_metadata' CPI method (CPI request ID: 'cpi-774755')
Task 414003 Started  Thu Sep 26 09:48:36 UTC 2019
Task 414003 Finished Thu Sep 26 10:01:46 UTC 2019

**Comment by thomas1206** [comment]
For every CPI call, we've an get storage account call in init. That would introduce too much storage account get operation and hit SRP throttling, especially in large scale deployment.

**Comment by ClaudiaBaur** [comment]
Please have a look at the related PR #628. Would appreciate if you could merge that part...
