### ISSUE TITLE
Disks/Images should be tagged like VM resources are

### ISSUE THREAD

**Issue by dsboulder** [cloudfoundry/bosh-azure-cpi-release#620]
**Is your feature request related to a problem? Please describe.**
Customers would like more reporting and policy enforcement of disks the way they are getting via tags on VMs.

**Describe the solution you'd like**
OS disks, persistent disks, and images should be tagged as well.

**Comment by pivotal-carlos-vasquez** [comment]
The customer is currently using Azure to manually tag Disk/Image resources as a work around. Their preference is for BOSH to apply these tags. 

Ticket Link: https://pivotal.lightning.force.com/lightning/r/Case/5000e00001dxo0yAAA/view

**Comment by ahelal** [comment]
Hi, Any update on this issue ?
