### ISSUE TITLE
Tags not getting removed from VMs when not sent in the update request

### ISSUE THREAD

**Issue by cynic89** [cloudfoundry/bosh-azure-cpi-release#624]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version:
BOSH     Version: 270.10.0
CF       Version: pks 1.7
Diego    Version: kubo-release-1.6.0

### Stemcell
Version: ubuntu-xenial 621.29
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [X] Azure
  - [ ] AzureChinaCloud
  - [ ] AzureUSGovernment
  - [ ] AzureGermanCloud
  - [ ] AzureStack
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (e.g. East US) Central US
- Subscription ID: CF-PKS-golf
- Resource Group Name: autumn-diver
- [ ] Use Managed Disks

### Issue Details
We are trying to implement iaas tags for VMs created using pks (https://www.pivotaltracker.com/story/show/169745939). When the vms are updated with a new set of tags, the tags that are not sent as part of this request are not getting removed. 

Tags are sent as dictionary of key value pairs in bosh manifest as shown below

### Logs (*Please redact all sensitive information in your logs*)
Manifest during create cluster
```
tags:
  luke: skywalker
  han: solo
  spock: ''
```
Manifest during update cluster
```
tags:
  luke: sw
  new_key: new_value
  spock: has_a_value
```
As you can see, the tag `han: solo` is not sent in the update request, which means it should be removed from the VM, but it's not happening. [This](https://portal.azure.com/#@pivotalio.onmicrosoft.com/resource/subscriptions/6ca04322-cc59-44e5-89b0-388b214d615d/resourceGroups/autumn-diver/providers/Microsoft.Compute/virtualMachines/1d520ad4-2e48-4609-9061-8c63f191a1e8/overview) is the VM where we tried this out.

### Repro steps (*if necessary, delete otherwise*)
1. Deploy PKS control plane from an opsman 2.8 env (https://autumn-diver.40.83.8.251.nip.io/) with a 1.7 tile that is built from iaas_tagging branch of pks-api (gs://raas-od-pks/iaas_tagging/pivotal-container-service-1.7.0-build.6.pivotal)   
2. Use the above pks control plane to create cluster with tags
```
curl -kvv -X POST \
  https://api.pks.com:9021/v1/clusters \
  -H 'Accept: application/json' \
  -H "Authorization: Bearer #Oauth_token#" \
  -H 'Content-Type: application/json' \
  -H 'Host: api.pks.com:9021' \
  -d '{
  "name": "cluster-with-tags-not-f2",
  "plan_name": "small",
  "parameters": {
    "kubernetes_master_host": "kub.master",
    "cluster_tags": [
      {
        "name": "han",
        "value": "solo"
      },
      {
        "name": "luke",
        "value": "skywalker"
      },
      {
        "name": "spock",
        "value": ""
      }
    ]
  }
}'
```
3. Update the above cluster with new tags 

```
curl -k -X PATCH \
  https://api.pks.com:9021/v1/clusters/cluster-with-tags-not-f2 \
  -H 'Accept: application/json' \
  -H "Authorization: Bearer #Oauth_token#" \
  -H 'Content-Type: application/json' \
  -H 'Host: api.pks.com:9021' \
  -d '{
        "cluster_tags": [
          {
            "name": "luke",
            "value": "sw"
          },
          {
            "name": "spock",
            "value": "has_a_value"
          },
          {
            "name": "new_key",
            "value": "new_value"
          }
        ]
      }'
```
4. Go to Azure console and check the vm. Notice that the `han: solo` tag is still present.

**Comment by h4xnoodle** [comment]
Created the attached PR for this fix. It's mutually exclusive to existing behaviour, so opening this decision up for discussion before changing the CPI.

There is a lot of motivation to take this change, but I worry that we risk breaking existing users. However, since bosh has only just started sending tags as part of a non-recreate instance update, I would think no one has been affected by this yet.

I will merge the PR soon if there are no problems and it goes through CI.
