### ISSUE TITLE
Make availability set deletion optional

### ISSUE THREAD

**Issue by hoegaarden** [cloudfoundry/bosh-azure-cpi-release#627]
**Is your feature request related to a problem? Please describe.**

We have a configuration where we get specific availability sets of a specific resource group pinned to a specific cluster. This allows us to make use of dedicated resources. We create all the AVSets up front and configure all instance group to deploy into those AVsets. If we now recreate certain deployments and BOSH finds a AVSet without any VMs left, it will delete it and our pinning will be gone. BOSH will recreate the AVSet once it creates new resources in them, but those won't be pinned now.

**Describe the solution you'd like**

I think an option like `delete_empty_availability_set` which defaults to `true` in [the global CPI settings](https://bosh.io/docs/azure-cpi/#global) might be reasonable.

**Describe alternatives you've considered**

We are looking into locking the AVSets we care about. We have not tested yet and don't know yet how the CPI behaves when it want's to delete a locked AVSet.
We also considered deploying "a dummy VM" into the AVSets in question. However this is a pretty heavy workaround.

**Comment by hoegaarden** [comment]
As far as I can see, this is the (only) place where the deletion is actually happening:
https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/8375dce86c6f3d3632061fa6657cba7b5f540a9c/src/bosh_azure_cpi/lib/cloud/azure/vms/vm_manager_availability_set.rb#L65-L70

**Comment by sneal** [comment]
Ideally the CPI should only cleanup or delete availability sets in which bosh creates. This could be handled via a tag on the AV set or similar.

**Comment by sneal** [comment]
What I proposed previously would be ideal for my situation, it's not backwards compatible therefore it's not tenable. One of @hoegaarden 's suggestions would be better.
