### ISSUE TITLE
BOSH Azure CPI could provide API to automatically add diego cell or Create VM on which containers can be deployed on . #4

### ISSUE THREAD

**Issue by viju2008** [cloudfoundry/bosh-azure-cpi-release#645]
### Detailed Description

BOSH Azure CPI could provide API  to automatically add diego cell or Create VM on which containers can be deployed on .

Currently a new diego cell has to be provisioned manually on Vsphere environment

### Context
. We wish to automate it using scripts so that based on load a new diego cell can be provisioned automatically on the underlying cloud technology using AZURE CPI

This will help users to not only scale containers but also the underlying VMs on which containers are deployed on

This will facilitate cloud burst scenarios , where organizations can burst to the cloud . They can keep minimal capacity in the azure cloud and using scripts can add or remove diego cells based on capacity required.

### Possible Implementation
Bosh azure CPI could provide apis to provision new  diego Cells . 

### Complexity

Medium

**Comment by beyhan** [comment]
We discussed this topic in https://github.com/cloudfoundry/bosh-deployment/issues/426.
