### ISSUE TITLE
Increase unit test coverage to 100%

### ISSUE THREAD

**Issue by Justin-W** [cloudfoundry/bosh-azure-cpi-release#652]
**Is your feature request related to a problem? Please describe.**

The PR template states that 100% code coverage is a requirement for every PR, but coverage seems to have gone down to ~99% quite a while ago.

**Describe the solution you'd like**

Ideally, more specs should be added to cover all currently-uncovered lines of code and return the unit test suite to 100% of lines covered.

**Note:** PR #651 added 9 Pending (unimplemented) unit specs (plus corresponding `TODO: coverage:` comments) to make it clearer which specs should be added to achieve this goal.
  - 6 of the 9 specs relate directly to lines of code currently without coverage.
  - the other 3 of 9 Pending specs added relate to effectively-uncovered code (i.e. sections of code which are technically covered by being executed by at least some unit specs, but for which there do not appear to be any specs which actually have relevant spec expectations which would cause spec failures if the code is defective), which happens to be near some of the uncovered lines of code. 
    * _Note:_ There are likely other sections of "effectively-uncovered code" (possibly many more) besides the ones related to these 3 recently-added Pending specs. I only noticed that these 3 specs were "missing" while trying to locate where the other 6 Pending specs should go.

**Describe alternatives you've considered**

Alternatively, the PR template message could be updated so that 100% is no longer a stated requirement for PR submission/approval.

**Additional context**

**Note:** The existing unit tests/specs would likely continue to pass even if any "effectively-uncovered code" sections (either those referenced above and/or others) are and/or become broken, and therefore the unit tests are likely to fail to detect a variety of potential functional regressions/defects affecting such code.

**Comment by rkoster** [comment]
I'm surprised there was a 100% coverage requirement, this is not something we have in the other bosh related repo's. Could you make a PR to remove the line about the 100% from: https://github.com/cloudfoundry/bosh-azure-cpi-release/tree/master/.github?

**Comment by Justin-W** [comment]
> I'm surprised there was a 100% coverage requirement, this is not something we have in the other bosh related repo's. Could you make a PR to remove the line about the 100% 

Done. See #654.
