### ISSUE TITLE
New BOSH Azure CPI release

### ISSUE THREAD

**Issue by vicwicker** [cloudfoundry/bosh-azure-cpi-release#661]
Hi,

This is not really an issue, but my team is interested in consuming https://github.com/cloudfoundry/bosh-azure-cpi-release/commit/6a95fbfb7f4686834a028be267d6f0d06650c60c

I would therefore like to ask if there is already a next release scheduled and if yes, when we can expect it; if not, do you think it would be possible to build a new release including the aforementioned change?

Thanks!
Victor

**Comment by rkoster** [comment]
This is currently blocked on: https://github.com/cloudfoundry/bosh-azure-cpi-release/pull/663 since CI is currently broken.

**Comment by friegger** [comment]
Is someone working on unblocking it?

**Comment by rkoster** [comment]
Above PR has been merged, and the cut release chore is almost at the top of the backlog. So expect a release to be cut this week.

**Comment by ragaskar** [comment]
Shipped, sorry for the delay. 

See https://bosh.io/releases/github.com/cloudfoundry/bosh-azure-cpi-release

**Comment by vicwicker** [comment]
> Shipped, sorry for the delay.
> 
> See https://bosh.io/releases/github.com/cloudfoundry/bosh-azure-cpi-release

Thanks!
