### ISSUE TITLE
Bosh director self snapshots are not being triggered

### ISSUE THREAD

**Issue by l-dimitrov** [cloudfoundry/bosh-azure-cpi-release#666]
### Versions (*please add them if you have more releases for this issue*)
CPI      Version: 38.0.0
BOSH     Version: 272.2.0
CF       Version: n/a
Diego    Version: n/a

### Stemcell
Version: 1.79
Distro:
  - [x] Ubuntu
  - [ ] CentOS

### Environment
- Azure Environment:
  - [x] Azure
    - Version: (e.g. 1712 update or build number 180106.1)
  - [ ] Others:
- Location: (all locations)
- Subscription ID: 
15152dfc-16bf-4d05-8d8d-7f045f7d9115 one of many
- Resource Group Name: SAP-SE-AZURE-CF-Audit-Logging-Live
- [ ] Use Managed Disks

### Issue Details
Hi Team,
We have the following scenario for AuditLogService. We are missing self snapshots for the Bosh director on all providers (Ali, GCP, Azure) beside AWS where the following is working fine:
...
enable_snapshots: true
self_snapshot_schedule: 0 1 * * * UTC
I see the snapshot jobs queued in the log:
cat scheduler.stdout.log | grep -i "SnapshotSelf"
I, [2022-03-08T15:01:14.575512 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: added scheduled job 'Bosh::Director::Jobs::SnapshotSelf' with interval '0 1 * * * UTC'
I, [2022-03-09T01:00:00.113901 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-10T01:00:00.306874 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-11T01:00:00.058503 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-12T01:00:00.167865 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-13T01:00:00.268429 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-14T01:00:00.211582 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-15T01:00:00.062717 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-16T01:00:00.182310 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
I, [2022-03-17T01:00:00.109313 #6](https://jtrack.wdf.sap.corp/browse/NGPBUG-181697#6) [] INFO – Director: enqueueing 'SnapshotSelf'
however no snapshots created for all but AWS provides.Any thoughts on why this might be happening? Other VMs are being backed up and the issue is only to bosh director selfsnapshot feature. 
Thanks and regards!

**Comment by l-dimitrov** [comment]
here is the error I get when debug is enabled:
./1469708/debug:51:D, [2022-06-03T01:00:02.774330 #27608] [task:1469708] DEBUG -- DirectorJobRunner: (0.000325s) (conn: 30560) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2022-06-03 01:00:02.772952+0000', "description" = 'scheduled SnapshotSelf', "result" = 'CPI error ''Bosh::Clouds::NotSupported'' with message ''Bosh::Clouds::NotSupported'' in ''current_vm_id'' CPI method (CPI request ID:...', "output" = '/var/vcap/store/director/tasks/1469708', "checkpoint_time" = '2022-06-03 01:00:01.708672+0000', "type" = 'snapshot_self', "username" = 'scheduler', "deployment_name" = NULL, "started_at" = '2022-06-03 01:00:01.708588+0000', "event_output" = '{"time":1654218002,"error":_### {"**code":100,"message":"CPI error ''Bosh::Clouds::NotSupported'' with message ''Bosh::Clouds::NotSupported'' in ''current_vm_id'' CPI method (CPI request ID: ''cpi-270416'')"}}**_
./1453713/debug:111:D, [2022-06-01T00:00:00.669934 #30863] [task:1453713] DEBUG -- DirectorJobRunner: (0.000794s) (conn: 1058560) SELECT "id", "output" FROM "tasks" WHERE (("type" = 'snapshot_self') AND ("state" NOT IN ('processing', 'queued'))) ORDER BY "id" DESC LIMIT 1 OFFSET 2000
./1462127/debug:51:D, [2022-06-02T01:00:02.881734 #27969] [task:1462127] DEBUG -- DirectorJobRunner: (0.000376s) (conn: 35680) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2022-06-02 01:00:02.880281+0000', "description" = 'scheduled SnapshotSelf', "result" = 'CPI error ''Bosh::Clouds::NotSupported'' with message ''Bosh::Clouds::NotSupported'' in ''current_vm_id'' CPI method (CPI request ID:...', "output" = '/var/vcap/store/director/tasks/1462127', "checkpoint_time" = '2022-06-02 01:00:01.696762+0000', "type" = 'snapshot_self', "username" = 'scheduler', "deployment_name" = NULL, "started_at" = '2022-06-02 01:00:01.696672+0000', "event_output" = '{"time":1654131602,"error":{"code":100,"message":"CPI error ''Bosh::Clouds::NotSupported'' with message ''Bosh::Clouds::NotSupported'' in ''current_vm_id'' CPI method (CPI request ID: ''cpi-597810'')"}}

**Comment by beyhan** [comment]
This operation is not supported on the listed IaaS'. So this never worked. This means that this is more a feature request.
