### ISSUE TITLE
Improve JSON parsing speed by using Oj or FastJsonParser

### ISSUE THREAD

**Issue by fearoffish** [cloudfoundry/bosh-azure-cpi-release#667]
At SAP, we have a huge amount of vms and in turn, network interfaces. We're seeing a significant wait time when rebuilding environments (which we do regularly) and we see a good amount of time wasted is in the JSON parsing of REST API calls. As an example, we see 3 calls to the API each returning 800Kb of JSON containing network interfaces which takes the BOSH process 12 seconds to parse (and call).

I propose a simple addition to the azure cpi, of the Oj rubygem which would improve that by roughly ⅓ .

I've run a benchmark of the JSON parsing in the [get_resources_by_url](https://github.com/cloudfoundry/bosh-azure-cpi-release/blob/master/src/bosh_azure_cpi/lib/cloud/azure/restapi/azure_client.rb#L151) method, using an 800Kb JSON file:

```
Warming up --------------------------------------
                json     1.000  i/100ms
                  oj     3.000  i/100ms
                fast     4.000  i/100ms
Calculating -------------------------------------
                json     18.872  (±21.2%) i/s -    179.000  in  10.030650s
                  oj     29.329  (±10.2%) i/s -    291.000  in  10.003598s
                fast     37.008  (±10.8%) i/s -    368.000  in  10.051131s

Comparison:
                fast:       37.0 i/s
                  oj:       29.3 i/s - 1.26x  (± 0.00) slower
                json:       18.9 i/s - 1.96x  (± 0.00) slower
```

In the benchmark I experiemented with the Oj gem and FastJsonParser. The largest increase in speed is from Oj, with a minor bump again if we use FastJsonParser. Honestly, I'm only proposing the Oj inclusion, it's much simpler and requires much less work.

I can create a PR if the community/maintainers would accept the PR, as I've created it already on an internal fork to play with. Real world results will be available soon too, once we push it to live and record the changes.

To be clear, the PR will do the following:

- Add the Oj gem to the Gemfile and vendor it
- Enable `Oj.mimic_JSON()` so we override the `JSON.parse` method therefore requiring no other code changes

What are your thoughts?

**Comment by mvach** [comment]
Hi,

inside SAP we are already testing Fastjsonparser for azure_cpi.
So I'll take here.

**Comment by rkoster** [comment]
This seems like a good idea. It should be relatively cheap to implement this behind a global cpi flag. Which would further derisk this feature.

**Comment by fearoffish** [comment]
We've been using this since July at SAP and we are seeing no problems. @rkoster Would we still need the CPI flag, or shall I just create a PR without?

**Comment by rkoster** [comment]
Just create a PR without it and see what the approvers think.

**Comment by cunnie** [comment]
Hey @mvach , could you please run `bin/vendor_gems` next time you bump a gem? Otherwise our CI comes to a screeching halt. Thanks.
