### ISSUE TITLE
Support the azure blobstore as external blobstore for bosh

### ISSUE THREAD

**Issue by max-soe** [cloudfoundry/bosh-azure-cpi-release#672]
**Is your feature request related to a problem? Please describe.**
On Azure we are still forced to use a local blobstore for bosh because there is no implementation to have an external blobstore in an Azure environment. For example for a multi-az setup it's necessary to have an external blobstore. 

**Describe the solution you'd like**
We can configure a external blobstore like for AWS and GCP: https://bosh.io/docs/release-blobstore/

**Comment by rkoster** [comment]
To be able to support the Azure native blobstore we would first need a bosh blobstore cli for it: https://github.com/cloudfoundry/bosh-s3cli

**Comment by mvach** [comment]
In 2018 there was already a very similar issue: https://github.com/cloudfoundry/bosh-azure-cpi-release/issues/545.
Issue https://github.com/cloudfoundry/bosh-azure-cpi-release/issues/545 proposed https://github.com/bingosummer/bosh-azureblobcli in addition to some integration changes.

**Comment by beyhan** [comment]
Just for reference what the CF Cloud Controller uses here https://github.com/cloudfoundry/cloud_controller_ng/blob/8173f4677b350b79dc5c985a3005119b9644919a/Gemfile.lock#L30-L40

**Comment by mvach** [comment]
Current development is happening in: https://github.com/mvach/bosh-azure-storage-cli

**Comment by mvach** [comment]
CLI development is now happening in: https://github.com/cloudfoundry/bosh-azure-storage-cli

**Comment by mvach** [comment]
Still missing is the director and agent integration.

**Comment by beyhan** [comment]
@mvach is this still in progress?

**Comment by mvach** [comment]
Hi, this is definitely still required, but I'm currently not taking care for the director integration because of time shortages. However if not me, then my team will take care latest in q3. I still hope to find time before.

**Comment by mvach** [comment]
The integration into the director and the agent consists of:

https://github.com/cloudfoundry/bosh/pull/2455
https://github.com/cloudfoundry/bosh/pull/2456
https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/295
https://github.com/cloudfoundry/bosh-stemcells-ci/pull/14
https://github.com/cloudfoundry/docs-bosh/pull/798

Right now only the docs PR still need to be merged.

**Comment by mvach** [comment]
Since all PRs are merged, I'm closing this issue.
